Vagrant.configure(2) do |config|

	config.vm.box_check_update = false
	config.vm.box = "hashicorp/bionic64"

	config.vm.network :private_network, ip: "192.168.42.110"
	config.vm.network :forwarded_port, guest: 80, host: 80
	config.vm.network :forwarded_port, guest: 8888, host: 8888
	config.vm.network :forwarded_port, guest: 9999, host: 9999

	config.vm.provider "virtualbox" do |v|
		v.memory = 10000
		v.cpus = 3
	end
	config.vm.provision "shell", privileged: true, path: "scripts/setup.sh"
end
