# -*- mode: ruby -*-
# vi: set ft=ruby :

# common config
NAME = 'pvivianS'
MEM = 2048
CPU = 2
BOX = "centos/8"
BOX_URL = "https://app.vagrantup.com/centos/boxes/8/versions/2011.0/providers/virtualbox.box"
BOX_AUTO_UPDATE = false

Vagrant.configure("2") do |config|

	config.vm.box = BOX
	config.vm.box_url = BOX_URL
	config.vm.box_check_update = BOX_AUTO_UPDATE
	config.vm.hostname = NAME
    config.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true
    config.vm.network "forwarded_port", guest: 8888, host: 8888, auto_correct: true

	config.vm.provider "virtualbox" do |v|
	    v.name = NAME
		v.memory = MEM
		v.cpus = CPU
	end

	config.vm.provision "shell", privileged: true, path: "scripts/setup.sh"
end